PREFIX schema: <http://schema.org/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>

# membres de l'ACD - Canadian Dance Assembly

CONSTRUCT {
    ?item wdt:P31 ?nature  ;
        a ?artsdata_type ;
        schema:disambiguatingDescription ?description ;
        schema:name ?itemLabel ;
        schema:memberOf wd:Q71859269 ;
        schema:sameAs ?adURI ;
        schema:url ?site .
}
WHERE {
    {
        SERVICE <https://query.wikidata.org/sparql>  {
            select distinct   ?item ?nature ?itemLabel ?description ?artsdata_type ?adURI ?site where {
                ?item wdt:P31 ?nature ;
                    rdfs:label ?itemLabel ;
                    schema:description ?description ;
                    wdt:P463 wd:Q71859269  .
                OPTIONAL {
                    ?item wdt:P856 ?site .
                }
                OPTIONAL {
                    ?item (wdt:P31/(wdt:P279*)) wd:Q5.
                    BIND(schema:Person AS ?artsdata_person_type)
                }
                BIND(COALESCE(?artsdata_person_type, schema:Organization) AS ?artsdata_type)
                OPTIONAL {
                    ?item wdt:P7627 ?adid .
                    bind(URI(CONCAT("http://kg.artsdata.ca/resource/",?adid)) as ?adURI)
                }
                FILTER(LANG(?itemLabel) IN ("fr","en")).
                FILTER(LANG(?description) IN ("fr","en")).
            }
        }
    }
}
