PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX pq: <http://www.wikidata.org/prop/qualifier/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bd: <http://www.bigdata.com/rdf#>

CONSTRUCT {
  ?ethnic skos:prefLabel ?ethnicLabel; skos:broader ?broader .
  ?broader skos:prefLabel ?broaderLabel  .
  }
WHERE {
  ?ethnic (wdt:P279*) wd:Q103817;
    wdt:P279 ?broader.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}

# Query editor: https://w.wiki/KHPe


# curl -s "https://raw.githubusercontent.com/culturecreates/artsdata-planet-wikidata/refs/heads/main/sparql/indigenous-people-taxonomy.sparql" | \
# curl -X POST \              
#   -H "Accept: text/turtle" \  
#   --data-urlencode "query@-" \       
#   "https://query.wikidata.org/sparql"